# Generated by Django 2.0.4 on 2018-04-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hamper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Hampers',
                'verbose_name': 'Hamper',
            },
        ),
    ]
