language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7-dev"

# command to install dependencies
install: "make"

cache: pip

# command to run tests and linter
script:
    - make unit-test
    - make pep8
